zgenet
======
Gustavo Ramos Rehermann
:toc:
:numbered:

This is a machine learning themed library for ZDoom ZScript, focusing
on basic neural networks and genetic evolution therefor.

If loaded as a mod, this will define a GeneZombie monster type, which
looks a lot like a zombie (possessed human, the pistol kind), but moves
around and, given enough time, evolves... hopefully!

== Getting Started

=== Using as Library

You must add this repository as a submodule of yours:

[source,console]
----
git submodule add "https://github.com/Gustavo6046/zgenet" zgenet
----

Then, assuming your main ZScript file is on the same directory,
include `zgenet/zgenet.zsc`. There is no need to load `zgenet`
as a separate mod - just include it as a subdirectory of yours!

For an example on how to implement this, see `ZScript.example`.

=== Run as Example

Run this mod as a folder, alongside Doom 2.

This is one of many ways to observe the example setup with the Gene Zombies:

[source,console]
----
git clone "https://github.com/Gustavo6046/zgenet" zgenet
gzdoom -iwad doom2.wad -file zgenet +map map30 +noclip +god2
----

Move to the main area to wake up the Icon of Sin, then issue `notarget` so
spawned monsters don't get distracted targeting you. Then, spawn a zombie
population as follows.

Running `summon GeneZombie 180` on the console will spawn a single zombie. This
will also remember its starting position. Then, instantly kill it with `mdk` to
trigger repopulation, which should spawn a few hundred zombies to replace it.

When first spawned, a zombie will have random behaviour, roaming around and probably
shooting around too.

Over time, they will slowly die of old age or from battle causes.
Once the population hits a minimal threshold, those who had
a decent performance will "breed" new zombies (by combining from two random picks,
the "genes" that determine each zombie's behaviour patterns), as well as a few additional
ones being generated randomly to maintain genetic diversity.

== Licensing

This project is licensed under the BSD 2-Clause License. For more info, see the `LICENSE`
file.
